<?php if (!defined('ABSPATH')) { exit; } ?>
<!DOCTYPE html><html <?php language_attributes(); ?>><head><meta charset="<?php bloginfo('charset'); ?>"><meta name="viewport" content="width=device-width, initial-scale=1"><?php wp_head(); ?></head><body <?php body_class('modern'); ?>><?php wp_body_open(); ?>
<a class="skip-link" href="#main">Перейти к содержимому</a>
<header><nav class="nav-bar" aria-label="Основная навигация"><a class="brand" href="#top">≈ water tours</a><button id="navToggle" aria-expanded="false" aria-controls="navLinks" aria-label="Открыть меню">Меню</button><ul id="navLinks"><li><a href="#about">О прогулке</a></li><li><a href="#rules">Как это работает</a></li><li><a href="#boat">Свой катер</a></li><li><a href="#faq">Вопросы</a></li><li><a class="button" href="#buy">Выбрать билеты ↗</a></li></ul></nav></header>
<main id="main"><section class="hero" id="top"><div class="hero-copy"><p class="eyebrow">WATER TOURS / РЕЧНЫЕ ПРОГУЛКИ</p><h1>Посмотрите на город<br><em>с воды.</em></h1><p class="lead">Оставьте привычные улицы на берегу. Выберите билеты на речную прогулку и найдите время для нового вида на город.</p><a class="button accent" href="#buy">Выбрать билеты ↗</a><a class="sub-link" href="#rules">Как действует билет ↓</a><p class="small">72 часа после оплаты · Один проход · Электронный билет</p></div><div class="scene" aria-hidden="true"><span class="sun"></span><span class="skyline"></span><span class="river"></span><span class="boat"></span><span class="caption">ДРУГОЙ РАКУРС.<br>ВАШ ГОРОД.</span></div></section>
<section class="container section" id="about"><p class="eyebrow">ПРОГУЛКА В ВАШЕМ РИТМЕ</p><div class="two-col"><h2>Меньше суеты.<br>Больше впечатлений.</h2><div><p class="large">Речная прогулка — повод замедлиться, побыть вместе и увидеть знакомый город иначе.</p><p>Билет действует три дня с момента подтверждённой оплаты. Вы выбираете отправление по расписанию в пределах этого срока. Конкретный рейс и место за билетом не закрепляются.</p></div></div></section>
<section class="tint section" id="rules"><div class="container"><p class="eyebrow">ОТ ВЫБОРА ДО ПОСАДКИ</p><h2>Три простых шага</h2><div class="steps"><article><span>01</span><h3>Выберите билеты</h3><p>Укажите количество взрослых, детских и льготных билетов. Проверьте итоговую сумму перед оформлением.</p></article><article><span>02</span><h3>Сохраните PDF</h3><p>После подтверждения оплаты скачайте билет с QR-кодом. Точное время окончания действия указано в билете.</p></article><article><span>03</span><h3>Покажите QR-код</h3><p>Предъявите билет сотруднику при посадке. Один билет даёт один проход и после погашения становится недействительным.</p></article></div></div></section>
<section class="container section two-col" id="buy"><div><p class="eyebrow">ВАША ПРОГУЛКА НАЧИНАЕТСЯ ЗДЕСЬ</p><h2>Билеты на<br>речную прогулку</h2><p>Купите билет на теплоход в Санкт-Петербурге онлайн — выберите состав компании и проверьте стоимость в форме заказа.</p><div class="validity"><strong>72</strong><span>часа действия<br>после подтверждения оплаты</span></div></div><div class="ticket"><div class="ticket-label">ЭЛЕКТРОННЫЙ БИЛЕТ <span>↗</span></div><h3>Одна прогулка.<br>Три дня на выбор.</h3><p>Взрослый, детский или льготный — выберите подходящие билеты в форме.</p><ul><li>PDF с QR-кодом</li><li>Один проход на прогулку</li><li>Без закрепления рейса и места</li></ul><?php if (shortcode_exists('water_tours_buy')) { echo do_shortcode('[water_tours_buy]'); } else { echo '<p>Оформление временно недоступно.</p>'; } ?><p class="small">Перед покупкой уточните маршрут, причал, расписание и условия выбранной категории билета.</p></div></section>
<section class="boat-rental section" id="boat"><div class="container boat-layout"><div class="boat-copy"><p class="eyebrow">КАТЕР ТОЛЬКО ДЛЯ ВАШЕЙ КОМПАНИИ</p><h2>Свой маршрут.<br><em>Свой ритм.</em></h2><p class="large">Арендуйте катер целиком для компании до шести гостей. Выберите продолжительность и предложите свой маршрут или попросите нас помочь.</p><div class="boat-facts"><span>до 6 гостей</span><span>один QR-билет</span><span>72 часа после оплаты</span></div></div><div class="rental-card"><div class="ticket-label">ЧАСТНАЯ ПРОГУЛКА <span>≈</span></div><div class="rental-price"><strong>3 500 ₽</strong><span>от 30 минут</span></div><div class="duration-grid" aria-label="Стоимость аренды"><span><b>30</b> мин<br>3 500 ₽</span><span><b>60</b> мин<br>6 000 ₽</span><span><b>90</b> мин<br>9 000 ₽</span><span><b>120</b> мин<br>11 000 ₽</span></div><?php if (shortcode_exists('water_tours_boat')) { echo do_shortcode('[water_tours_boat]'); } else { echo '<p class="rental-unavailable">Оформление аренды скоро появится.</p>'; } ?><p class="small">Один заказ оформляется на всю компанию. Время выхода и маршрут согласуются отдельно.</p></div></div></section>
<section class="section faq-section" id="faq"><div class="container two-col"><div><p class="eyebrow">ПОЛЕЗНО ЗНАТЬ</p><h2>Перед<br>прогулкой</h2></div><div><?php foreach (water_tours_home_faq() as $question => $answer) : ?><details><summary><?php echo esc_html($question); ?></summary><p><?php echo esc_html($answer); ?></p></details><?php endforeach; ?></div></div></section>
<section class="container section final-cta"><p class="eyebrow">ДОБАВЬТЕ В ДЕНЬ НОВЫЙ ВИД</p><h2>Встретимся у воды.</h2><a class="button accent" href="#buy">Выбрать билеты ↗</a></section></main>
<footer><div class="container footer-inner"><a class="brand" href="#top">≈ water tours</a><span>Речные прогулки. Электронные билеты.</span><a href="#rules">Правила билета</a><?php if (get_privacy_policy_url()) : ?><a href="<?php echo esc_url(get_privacy_policy_url()); ?>">Конфиденциальность</a><?php endif; ?></div></footer><?php wp_footer(); ?></body></html>
