server:
  port: 8087
yookassa:
  shopId: ${YOOKASSA_SHOP_ID}
  secretKey: ${YOOKASSA_SECRET_KEY}
spring:
  application:
    name : testHtmx
  datasource:
    url: jdbc:postgresql://localhost:5430/htmxserver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name:  org.postgresql.Driver
  mail:
    host: smtp.yandex.ru
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
              required: true
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
        ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  redis:
    host: host.docker.internal
    port: 6379

values:
  ticket:
      price:
          child: 599
          senior: 1099
          discount: 799
logging:
  level:
    com:
      watertours:
          project:
            controller: debug
            service: debug
            repository: debug
    level:
      org:
        springframework:
          boot:
            web:
              embedded: WARN

  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
  file:
    name: logs/waterTours.log
email:
  confirmation:
    ttl-minutes: 3